Remove MSIZE from DiskAddress
ava-labs/firewood pull request #335
Opened 2023-10-30 18:54 UTC by rkuris

Now actually uses the size of the struture for computing how many bytes to write.

2023-10-30 19:50 UTC, richardpringle requested changes
I know it would be insane for someone to mess this up, but if you use the same constant, it's a little more clear that the function-return, view-size, and error all contain the exact same thing

2023-10-30 19:50 UTC, richardpringle commented on shale/src/disk_address.rs
> -    const MSIZE: u64 = 8;
```rust
const MSIZE: u64 = size_of::<Self>() as u64;
```
Then, you can leave the rest of the code as it was. 

You still want the three places where this was previously used to be the same value, so it doesn't make sense to call the same function three different times.

2023-10-31 05:09 UTC, richardpringle approved these changes

2023-10-31 06:53 UTC, xinifinity approved these changes

2023-10-31 14:02 UTC, merged