Make `MerkleKeyValueStream` handle branches with values
ava-labs/firewood pull request #424
Opened 2023-12-07 23:03 UTC by richardpringle

This was not the easiest thing to implement. Once I got the tests passing, I went over it a few times. 

It actually looks like we should move the starting logic into the `get_iter` method, but I will leave that for another day. I honestly tried to make this a much smaller change, but there was no way to get it to work without re-writing everything.

2023-12-07 23:04 UTC, richardpringle commented on firewood/src/merkle.rs
> +    pub(super) fn create_test_merkle() -> Merkle<CompactSpace<Node, DynamicMem>, Bincode> {
This isn't ideal but it was the quickest way to re-use this code.

2023-12-07 23:19 UTC, richardpringle commented on firewood/src/merkle/stream.rs
> +                                let value = branch.value.as_ref().map(|v| v.to_vec());
🤔, this is a little awkward. `get_node_by_key_with_callbacks` will only return nodes with data. 

This will go away once #399 is implemented.

2023-12-07 23:19 UTC, richardpringle commented on firewood/src/merkle/stream.rs
> +                    if (key.as_slice()) < (key_from_parents.as_slice()) {
Clippy should have removed these brackets for me. Leaving a comment here for myself

2023-12-11 15:43 UTC, rkuris requested changes

2023-12-11 15:43 UTC, rkuris commented on firewood/src/merkle/stream.rs
> +        next_result: Option<(Vec<u8>, Vec<u8>)>,
The state should not include the next key, only location information as to where we are.

As we discussed in-person, we should attempt to fix the existing stream iterator unless there's some reason why we can't.

Next steps are to add a unit test and debug the existing stream iterator code.

2023-12-11 19:21 UTC, closed without merging